#include "../engine/flow/FlowGraphCodegen.h"
#include <iostream>
#include <cassert>

// --- Test: codegen produces non-empty output for a valid IR ---

void test_flow_codegen_nonempty() {
    atlas::flow::FlowGraphIR ir;
    ir.name = "TestGraph";
    ir.graphType = "Gameplay";
    atlas::flow::FlowNodeIR node;
    node.id = 1;
    node.type = "State";
    node.category = "Flow";
    node.properties.push_back({"stateName", "Idle"});
    ir.nodes.push_back(node);

    std::string code = atlas::flow::FlowGraphCodegen::Generate(ir);
    assert(!code.empty());
    std::cout << "[PASS] test_flow_codegen_nonempty" << std::endl;
}

// --- Test: generated code contains expected function signature ---

void test_flow_codegen_function_signature() {
    atlas::flow::FlowGraphIR ir;
    ir.name = "MyGraph";
    ir.graphType = "Gameplay";
    atlas::flow::FlowNodeIR node;
    node.id = 1;
    node.type = "State";
    node.category = "Flow";
    ir.nodes.push_back(node);

    std::string code = atlas::flow::FlowGraphCodegen::Generate(ir);
    assert(code.find("void Execute_MyGraph") != std::string::npos);
    assert(code.find("const FlowContext& ctx") != std::string::npos);
    assert(code.find("std::unordered_map<uint64_t, FlowValue>& outputs") != std::string::npos);
    std::cout << "[PASS] test_flow_codegen_function_signature" << std::endl;
}

// --- Test: empty IR produces valid minimal code ---

void test_flow_codegen_empty_graph() {
    atlas::flow::FlowGraphIR ir;
    ir.name = "Empty";
    ir.graphType = "UI";

    std::string code = atlas::flow::FlowGraphCodegen::Generate(ir);
    assert(!code.empty());
    assert(code.find("Execute_Empty") != std::string::npos);
    assert(code.find("Empty graph") != std::string::npos);
    std::cout << "[PASS] test_flow_codegen_empty_graph" << std::endl;
}

// --- Test: node properties appear in generated code ---

void test_flow_codegen_node_properties() {
    atlas::flow::FlowGraphIR ir;
    ir.name = "PropTest";
    ir.graphType = "Gameplay";
    atlas::flow::FlowNodeIR node;
    node.id = 1;
    node.type = "State";
    node.category = "Flow";
    node.properties.push_back({"stateName", "MainMenu"});
    ir.nodes.push_back(node);

    std::string code = atlas::flow::FlowGraphCodegen::Generate(ir);
    assert(code.find("MainMenu") != std::string::npos);
    std::cout << "[PASS] test_flow_codegen_node_properties" << std::endl;
}

// --- Test: edge wiring shows up in generated code ---

void test_flow_codegen_edge_wiring() {
    atlas::flow::FlowGraphIR ir;
    ir.name = "EdgeTest";
    ir.graphType = "AI";

    atlas::flow::FlowNodeIR stateNode;
    stateNode.id = 1;
    stateNode.type = "State";
    stateNode.category = "Flow";
    stateNode.properties.push_back({"stateName", "Combat"});
    ir.nodes.push_back(stateNode);

    atlas::flow::FlowNodeIR condNode;
    condNode.id = 2;
    condNode.type = "Condition";
    condNode.category = "Logic";
    ir.nodes.push_back(condNode);

    ir.edges.push_back({1, 0, 2, 0});

    std::string code = atlas::flow::FlowGraphCodegen::Generate(ir);
    assert(code.find("wire: node 1 port 0 -> node 2 port 0") != std::string::npos);
    std::cout << "[PASS] test_flow_codegen_edge_wiring" << std::endl;
}

// --- Test: all four node types generate code ---

void test_flow_codegen_all_node_types() {
    atlas::flow::FlowGraphIR ir;
    ir.name = "AllTypes";
    ir.graphType = "Gameplay";

    atlas::flow::FlowNodeIR state;
    state.id = 1; state.type = "State"; state.category = "Flow";
    state.properties.push_back({"stateName", "Idle"});
    ir.nodes.push_back(state);

    atlas::flow::FlowNodeIR cond;
    cond.id = 2; cond.type = "Condition"; cond.category = "Logic";
    ir.nodes.push_back(cond);

    atlas::flow::FlowNodeIR timer;
    timer.id = 3; timer.type = "Timer"; timer.category = "Control";
    ir.nodes.push_back(timer);

    atlas::flow::FlowNodeIR trans;
    trans.id = 4; trans.type = "Transition"; trans.category = "Flow";
    ir.nodes.push_back(trans);

    std::string code = atlas::flow::FlowGraphCodegen::Generate(ir);
    assert(code.find("Node 1: State") != std::string::npos);
    assert(code.find("Node 2: Condition") != std::string::npos);
    assert(code.find("Node 3: Timer") != std::string::npos);
    assert(code.find("Node 4: Transition") != std::string::npos);
    std::cout << "[PASS] test_flow_codegen_all_node_types" << std::endl;
}

// --- Test: header comment includes graph name and type ---

void test_flow_codegen_header_comment() {
    atlas::flow::FlowGraphIR ir;
    ir.name = "HeroAI";
    ir.graphType = "AI";

    std::string code = atlas::flow::FlowGraphCodegen::Generate(ir);
    assert(code.find("Generated by AtlasForge FlowGraphCodegen") != std::string::npos);
    assert(code.find("\"HeroAI\"") != std::string::npos);
    assert(code.find("(AI)") != std::string::npos);
    std::cout << "[PASS] test_flow_codegen_header_comment" << std::endl;
}
